# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHinjxZkOh-zbA4PynDbL4M9mhEAE9ku
"""

import cv2
import numpy as np

img1 = cv2.imread("Resources/a_1.jpg")
img2 = cv2.imread("Resources/a_2.jpg")
img3 = cv2.imread("Resources/a_3.jpg")
img4 = cv2.imread("Resources/a_4.jpg")
img5 = cv2.imread("Resources/a_5.jpg")

# Concatenate images of same width vertically
""""cv2.vconcat() used"""
img_v = cv2.vconcat([img1, img2])

# Concatenate images of different widths vertically
"""" A function to resize the image """
def vconcat_resize_min(im_list, interpolation=cv2.INTER_CUBIC):
    w_min = min(im.shape[1] for im in im_list)
    im_list_resize = [cv2.resize(im, (w_min, int(im.shape[0] * w_min / im.shape[1])), interpolation=interpolation)
                      for im in im_list]
    return cv2.vconcat(im_list_resize)

img_v_resize = vconcat_resize_min([img1, img2, img3,img4,img5])


# show the output image
cv2.imwrite('vconcat_resize.jpg', img_v_resize)

#cv2.imshow("Vertical join same width ", img_v)
#cv2.imshow("Vertical join Different width", img_v_resize)
#cv2.imshow("Horizontal join same height ", img_h)
# cv2.imshow("Horizontal join Different height", img_h_resize)
# cv2.waitKey(0)